=== kykz159/Project-Ghost/Engine/Plugins/VirtualProduction/CaptureManager/CaptureManagerCore/Content/TakeMetadata/Schema/v1.0.json
{
  "$schema": "https://json-schema.org/draft-04/schema",
  
  "definitions": {

    "VersionFormat": {
      "type": "object",
      "properties": {
        "Major": {
          "type": "integer",
          "minimum": 0
        },
        "Minor": {
          "type": "integer",
          "minimum": 0
        },
        "Patch": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "Major",
        "Minor",
        "Patch"
      ]
    },

    "TimecodeFormat": {
      "type": "string",
      "pattern": "(([0-1][0-9]|[0-2][0-3]):)([0-5][0-9]:)([0-5][0-9][:;])([0-5][0-9])(\\.[0-9]{3})?"
    },

    "UniqueIdFormat": {
      "type": "string",
      "format": "uuid",
      "pattern": "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    },

    "VideoOrImageSequence": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "UserId": {
            "type": "string"
          },
          "Path": {
            "type": "string"
          },
          "PathType": {
            "type": "string",
            "enum": [
              "File",
              "Folder"
            ]
          },
          "Format": {
            "type": "string"
          },
          "Orientation": {
            "type": "string",
            "enum": [
              "Original",
              "CW90",
              "CW180",
              "CW270"
            ]
          },
          "FramesCount": {
            "type": "integer",
            "minimum": 0
          },
          "DroppedFrames": {
            "type": "array",
            "items": {
              "type": "integer",
              "minimum": 0
            }
          },
          "FrameHeight": {
            "type": "integer",
            "minimum": 1
          },
          "FrameWidth": {
            "type": "integer",
            "minimum": 1
          },
          "FrameRate": {
            "type": "number",
            "minimum": 0
          },
          "TimecodeStart": {
            "$ref": "#/definitions/TimecodeFormat"
          },
          "TimecodeRate": {
            "type": "number",
            "minimum": 0
          }
        },
        "required": [
          "UserId",
          "Path",
          "PathType",
          "Format",
          "Orientation",
          "FramesCount",
          "DroppedFrames",
          "FrameHeight",
          "FrameWidth",
          "FrameRate",
          "TimecodeStart",
          "TimecodeRate"
        ]
      }
    }

  },
  

  "type": "object",
  "properties": {
    "Version": {
      "$ref": "version.json#/definitions/SchemaVersionFormat"
    },
    "DateTime": {
      "type": "string",
      "pattern": "[0-9]{4}-[01][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]+([+-][0-2][0-9]:[0-5][0-9]|Z)"
    },
    "Thumbnail": {
      "type": "string"
    },
    "UniqueId": {
      "$ref": "#/definitions/UniqueIdFormat"
    },
    "TakeNumber": {
      "type": "integer",
      "minimum": 1
    },
    "Slate": {
      "type": "string"
    },
    "Device": {
      "type": "object",
      "properties": {
        "Type": {
          "type": "string"
        },
        "Model": {
          "type": "string"
        },
        "UserId": {
          "type": "string"
        },
        "Platform": {
          "type": "object",
          "properties": {
            "Name": {
              "type": "string",
              "enum": [
                "iOS",
                "Android",
                "Windows",
                "Linux",
                "macOS"
              ]
            },
            "Version": {
              "$ref": "#/definitions/VersionFormat"
            }
          },
          "required": [
            "Name",
            "Version"
          ]
        },
        "Software": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "Name": {
                  "type": "string"
                },
                "Version": {
                  "$ref": "#/definitions/VersionFormat"
                }
              },
              "required": [
                "Name",
                "Version"
              ]
            }
          ]
        }
      },
      "required": [
        "Type",
        "Model",
        "UserId",
        "Platform",
        "Software"
      ]
    },
    "Video": {
      "$ref": "#/definitions/VideoOrImageSequence"
    },
    "Depth": {
      "$ref": "#/definitions/VideoOrImageSequence"
    },

    "Calibration": {
      "type": "object",
      "properties": {
        "Path": {
          "type": "string"
        }
      },
      "required": [
        "Path"
      ]
    },
    "Audio": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "UserId": {
              "type": "string"
            },
            "Path": {
              "type": "string"
            },
            "Duration": {
              "type": "number",
              "minimum": 0
            },
            "TimecodeRate": {
              "type": "number",
              "minimum": 0
            },
            "TimecodeStart": {
              "$ref": "#/definitions/TimecodeFormat"
            }
          },
          "required": [
            "UserId",
            "Path",
            "TimecodeRate",
            "TimecodeStart"
          ]
        }
      ]
    },
    "Animation": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "Path": {
              "type": "string"
            },
            "Format": {
              "type": "string"
            }
          },
          "required": [
            "Path",
            "Format"
          ]
        }
      ]
    }
  },
  "required": [
    "Version",
    "DateTime",
    "UniqueId",
    "TakeNumber",
    "Slate",
    "Device"
  ]
}

=== kykz159/Project-Ghost/Engine/Plugins/VirtualProduction/CaptureManager/CaptureManagerApp/Content/CaptureManagerPipeline/Take_4/take.json
{
    "Version": {
        "Major": 1,
        "Minor": 0
    },
    "DateTime": "2023-02-27T08:57:17.796000Z",
    "UniqueId": "a78613f3-e660-47e4-af6a-1298cde7c947",
    "TakeNumber": 4,
    "Slate": "Take",
    "Device": {
        "Type": "iPhone",
        "Model": "iPhone13,3",
        "UserId": "UserDev001",
        "Platform": {
            "Name": "iOS",
            "Version": {
                "Major": 17,
                "Minor": 2,
                "Patch": 1
            }
        },
        "Software": [
            {
                "Name": "Live Link Face",
                "Version": {
                    "Major": 2,
                    "Minor": 5,
                    "Patch": 7
                }
            }
        ]
    },
	"Video": [],
    "Audio": [
        {
			"UserId": "Mic",
			"Path": "audio.wav",
			"Duration": 5.4,
			"TimecodeRate": 60.0,
			"TimecodeStart": "09:01:41:08.600"
        }
    ]
}

=== kykz159/Project-Ghost/Engine/Plugins/VirtualProduction/CaptureManager/CaptureManagerApp/Content/CaptureManagerPipeline/Take_5/take.json
{
    "Version": {
        "Major": 1,
        "Minor": 0
    },
    "DateTime": "2023-02-27T08:57:17.796000Z",
    "UniqueId": "a78613f3-e660-47e4-af6a-1298cde7c947",
    "TakeNumber": 5,
    "Slate": "Take",
    "Device": {
        "Type": "iPhone",
        "Model": "iPhone13,3",
        "UserId": "UserDev001",
        "Platform": {
            "Name": "iOS",
            "Version": {
                "Major": 17,
                "Minor": 2,
                "Patch": 1
            }
        },
        "Software": [
            {
                "Name": "Live Link Face",
                "Version": {
                    "Major": 2,
                    "Minor": 5,
                    "Patch": 7
                }
            }
        ]
    },
    "Depth": [
        {
            "UserId": "Camera",
            "Path": "depth_data.bin",
            "PathType": "File",
            "Format": "bin",
            "Orientation": "CW270",
            "FramesCount": 1,
            "DroppedFrames": [],
            "FrameHeight": 360,
            "FrameWidth": 640,
            "FrameRate": 30,
            "TimecodeStart": "09:01:41:01.300",
            "TimecodeRate": 30
        }
    ]
}

=== kykz159/Project-Ghost/Engine/Plugins/VirtualProduction/CaptureManager/CaptureManagerApp/Content/CaptureManagerPipeline/Take_2/take.json
{
    "Version": {
        "Major": 1,
        "Minor": 0
    },
    "DateTime": "2023-02-27T08:57:17.796000Z",
    "UniqueId": "a78613f3-e660-47e4-af6a-1298cde7c947",
    "TakeNumber": 2,
    "Slate": "Take",
    "Device": {
        "Type": "iPhone",
        "Model": "iPhone13,3",
        "UserId": "UserDev001",
        "Platform": {
            "Name": "iOS",
            "Version": {
                "Major": 17,
                "Minor": 2,
                "Patch": 1
            }
        },
        "Software": [
            {
                "Name": "Live Link Face",
                "Version": {
                    "Major": 2,
                    "Minor": 5,
                    "Patch": 7
                }
            }
        ]
    },
    "Video": [
        {
            "UserId": "Camera_1",
            "Path": "Test_Take_2_Camera_1.mov",
            "PathType": "File",
            "Format": "mov",
            "Orientation": "CW90",
            "FramesCount": 1,
            "DroppedFrames": [],
            "FrameHeight": 720,
            "FrameWidth": 1280,
            "FrameRate": 60,
            "TimecodeStart": "09:01:41:01.300",
            "TimecodeRate": 60
        },
        {
            "UserId": "Camera_2",
            "Path": "Test_Take_2_Camera_2.mov",
            "PathType": "File",
            "Format": "mov",
            "Orientation": "CW90",
            "FramesCount": 1,
            "DroppedFrames": [],
            "FrameHeight": 720,
            "FrameWidth": 1280,
            "FrameRate": 60,
            "TimecodeStart": "09:01:41:01.300",
            "TimecodeRate": 60
        }
    ]
}
